/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientAccount {
  'id' : bigint,
  'pnl' : number,
  'status' : string,
  'name' : string,
  'capital' : number,
}
export interface InstrumentStats {
  'chartData' : Array<PriceData>,
  'scalps' : bigint,
  'weeklyPnL' : number,
  'wins' : bigint,
  'losses' : bigint,
  'symbol' : string,
}
export interface PerformanceMetrics {
  'totalTrades' : bigint,
  'winRatio' : number,
  'lastUpdated' : bigint,
  'monthlyPnL' : number,
  'overallPnL' : number,
}
export interface PriceData {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'time' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClientAccount' : ActorMethod<[ClientAccount], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteClientAccount' : ActorMethod<[bigint], undefined>,
  'editClientAccount' : ActorMethod<[bigint, ClientAccount], undefined>,
  'getAllClientAccounts' : ActorMethod<[], Array<ClientAccount>>,
  'getAllInstrumentStats' : ActorMethod<[], Array<InstrumentStats>>,
  'getAllInstrumentStatsSortedByScalps' : ActorMethod<
    [],
    Array<InstrumentStats>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientAccount' : ActorMethod<[bigint], [] | [ClientAccount]>,
  'getInstrumentStats' : ActorMethod<[string], InstrumentStats>,
  'getPerformanceMetrics' : ActorMethod<[], PerformanceMetrics>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyScalpSummary' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInstrumentStats' : ActorMethod<[string, InstrumentStats], undefined>,
  'updatePerformanceMetrics' : ActorMethod<[PerformanceMetrics], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];