/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClientAccount = IDL.Record({
  'id' : IDL.Nat,
  'pnl' : IDL.Float64,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'capital' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PriceData = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'time' : IDL.Int,
});
export const InstrumentStats = IDL.Record({
  'chartData' : IDL.Vec(PriceData),
  'scalps' : IDL.Nat,
  'weeklyPnL' : IDL.Float64,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PerformanceMetrics = IDL.Record({
  'totalTrades' : IDL.Nat,
  'winRatio' : IDL.Float64,
  'lastUpdated' : IDL.Int,
  'monthlyPnL' : IDL.Float64,
  'overallPnL' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClientAccount' : IDL.Func([ClientAccount], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteClientAccount' : IDL.Func([IDL.Nat], [], []),
  'editClientAccount' : IDL.Func([IDL.Nat, ClientAccount], [], []),
  'getAllClientAccounts' : IDL.Func([], [IDL.Vec(ClientAccount)], ['query']),
  'getAllInstrumentStats' : IDL.Func([], [IDL.Vec(InstrumentStats)], ['query']),
  'getAllInstrumentStatsSortedByScalps' : IDL.Func(
      [],
      [IDL.Vec(InstrumentStats)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientAccount' : IDL.Func([IDL.Nat], [IDL.Opt(ClientAccount)], ['query']),
  'getInstrumentStats' : IDL.Func([IDL.Text], [InstrumentStats], ['query']),
  'getPerformanceMetrics' : IDL.Func([], [PerformanceMetrics], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyScalpSummary' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInstrumentStats' : IDL.Func([IDL.Text, InstrumentStats], [], []),
  'updatePerformanceMetrics' : IDL.Func([PerformanceMetrics], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClientAccount = IDL.Record({
    'id' : IDL.Nat,
    'pnl' : IDL.Float64,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'capital' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PriceData = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'time' : IDL.Int,
  });
  const InstrumentStats = IDL.Record({
    'chartData' : IDL.Vec(PriceData),
    'scalps' : IDL.Nat,
    'weeklyPnL' : IDL.Float64,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PerformanceMetrics = IDL.Record({
    'totalTrades' : IDL.Nat,
    'winRatio' : IDL.Float64,
    'lastUpdated' : IDL.Int,
    'monthlyPnL' : IDL.Float64,
    'overallPnL' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClientAccount' : IDL.Func([ClientAccount], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteClientAccount' : IDL.Func([IDL.Nat], [], []),
    'editClientAccount' : IDL.Func([IDL.Nat, ClientAccount], [], []),
    'getAllClientAccounts' : IDL.Func([], [IDL.Vec(ClientAccount)], ['query']),
    'getAllInstrumentStats' : IDL.Func(
        [],
        [IDL.Vec(InstrumentStats)],
        ['query'],
      ),
    'getAllInstrumentStatsSortedByScalps' : IDL.Func(
        [],
        [IDL.Vec(InstrumentStats)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientAccount' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ClientAccount)],
        ['query'],
      ),
    'getInstrumentStats' : IDL.Func([IDL.Text], [InstrumentStats], ['query']),
    'getPerformanceMetrics' : IDL.Func([], [PerformanceMetrics], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyScalpSummary' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInstrumentStats' : IDL.Func([IDL.Text, InstrumentStats], [], []),
    'updatePerformanceMetrics' : IDL.Func([PerformanceMetrics], [], []),
  });
};

export const init = ({ IDL }) => { return []; };